sudo: false
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'openmpi-dev', 'openmpi-bin']

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6', 'openmpi-dev', 'openmpi-bin']

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  # clang 3.4
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi

script: ./configure -noparallel && make && make check

branches:
  only:
    - master