language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - clang-3.6
      - openmpi-dev
      - openmpi-bin

install:
  # g++4.8.1
  - [ "$CXX" = "g++" ] && export CXX="g++-5.0"
  # clang 3.4
  - [ "$CXX" = "clang++" ] && export CXX="clang++-3.6"

script: ./configure -noparallel && make && make check

branches:
  only:
    - master

notifications:
  email: true